package com.kietngo.example.notificationlogs.model

import android.os.Parcel
import android.os.Parcelable
import com.google.gson.annotations.SerializedName

data class Posted(
    @SerializedName("packageName") val packageName : String?,
    @SerializedName("postTime") val postTime: String?,
    @SerializedName("systemTime") val systemTime: String?,
    @SerializedName("offset") val offset : Long?,
    @SerializedName("version") val version : Int?,
    @SerializedName("sdk") val sdk : Int?,
    @SerializedName("isOngoing") val isOnGoing: String?,
    @SerializedName("isClearable") val isClearable : String?,
    @SerializedName("when") val whenNotification : String?,
    @SerializedName("number") val number : Int?,
    @SerializedName("flags") val flags : Int?,
    @SerializedName("defaults") val defaults: Int?,
    @SerializedName("ledARGB") val  ledARGB: Int?,
    @SerializedName("ledOn") val ledOn: Int?,
    @SerializedName("ledOff") val ledOff: Int?,
    @SerializedName("ringerMode") val ringerMode: Int?,
    @SerializedName("isScreenMode") val isScreenMode: String?,
    @SerializedName("isScreenOn") val isScreenOn: String?,
    @SerializedName("batteryLevel") val batteryLevel: Int?,
    @SerializedName("batteryStatus") val batteryStatus : String?,
    @SerializedName("isConnected") val isConnected: String?,
    @SerializedName("connectionType") val connectionType: String?,
    @SerializedName("hasAppointment") val hasAppointment: String?,
    @SerializedName("isGroupSummary") val isGroupSummary: String?,
    @SerializedName("category") val category: String?,
    @SerializedName("actionCount") val actionCount: Int?,
    @SerializedName("isLocalOnly") val isLocalOnly: String?,
    @SerializedName("people") val people: Int?,
    @SerializedName("tickerText") val tickerText: String?,
    @SerializedName("title") val title: String?,
    @SerializedName("titleBig") val titleBig: String?,
    @SerializedName("text") val text: String?,
    @SerializedName("textBig") val textBig: String?,
    @SerializedName("textInfo") val textInfo: String?,
    @SerializedName("textSub") val textSub: String?,
    @SerializedName("textSummary") val textSummary: String?,
    @SerializedName("appName") val appName: String?,
    @SerializedName("priority") val priority: Int?,
    @SerializedName("nid") val nid: String?,
    @SerializedName("key") val key: String?,
    @SerializedName("visibility") val visibility: String?,
    @SerializedName("color") val color: String?,
    @SerializedName("interruptionFilter") val interruptionFilter: String?,
    @SerializedName("listenerHints") val listenerHints: String?,
    @SerializedName("matchesInterruptionFilter") val matchesInterruptionFilter: String?,
)